// Buildless DOM and asset checks. Does not run a browser or send any enquiry.
const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'../preview');
const source=fs.readFileSync(path.join(root,'projects.js'),'utf8')+'\n'+fs.readFileSync(path.join(root,'site.js'),'utf8').replace(/render\(\);\s*$/,'');
const routes=['','work','services','method','about','start-a-project','privacy','terms','404.html','work/lacteo','work/elleye','work/kitch','work/cadoo','work/almonby','work/indigo-moss','work/noctra','work/fluffy-muffin','work/voda-soda','work/lushy'];
const result=[];
for(const route of routes){const filename=route==='404.html'?route:route?route+'/index.html':'index.html';const context={document:{baseURI:'https://example.test/preview/'},location:{pathname:'/preview/'+filename,search:''},URL,URLSearchParams};vm.createContext(context);vm.runInContext(source,context);const markup=vm.runInContext(`nav()+(currentRoute().startsWith('work/')?projectPage(projects.find(p=>p.slug===currentRoute().slice(5))):({'':home,work:workPage,services:servicesPage,method:methodPage,about:aboutPage,'start-a-project':startPage,privacy:privacyPage,terms:termsPage}[currentRoute()]||notFoundPage)())+footer()`,context);if((markup.match(/<h1[ >]/g)||[]).length!==1)throw Error('Invalid h1 '+route);if(/undefined|src=""|NaN/.test(markup))throw Error('Invalid markup '+route);result.push({route,filename,markup});}
const allProjectMedia=vm.runInNewContext(fs.readFileSync(path.join(root,'projects.js'),'utf8')+'; projects.map(p=>({slug:p.slug,count:p.blocks.filter(b=>["image","pair","gallery","feature"].includes(b.type)).reduce((n,b)=>n+(b.images?.length||1),0)}))');
for(const p of allProjectMedia){const markup=result.find(r=>r.route==='work/'+p.slug).markup;const count=(markup.match(/class="image-expand"/g)||[]).length;if(count!==p.count)throw Error(`Missing media ${p.slug}: ${count}/${p.count}`)}
for(const r of result){for(const match of r.markup.matchAll(/(?:src|href)="([^"]+)"/g)){const link=match[1];if(/^(?:https?:|mailto:|#)/.test(link))continue;const target=decodeURIComponent(link.split(/[?#]/)[0]).replace(/^\/preview\//,'');if(!fs.existsSync(path.join(root,target)))throw Error(`Broken resource ${r.route}: ${target}`)}}
const checks=vm.createContext({});vm.runInContext(source,checks);const message=vm.runInContext(`buildEnquiry(new Map([['name','Test'],['email','test@example.test'],['question','A & B?'],['service','Venture Diagnostic'],['stage','Early venture or idea'],['budget','Not sure yet'],['context','']]))`,checks);if(!message.includes('A & B?')||!message.includes('test@example.test'))throw Error('Enquiry body missing fields');
const destination=process.argv[2];if(destination){fs.mkdirSync(destination,{recursive:true});for(const r of result)fs.writeFileSync(path.join(destination,r.route.replaceAll('/','-')||'home')+'.html',r.markup)}
console.log(JSON.stringify({pages:result.length,caseStudies:allProjectMedia.length,caseImages:allProjectMedia.reduce((n,p)=>n+p.count,0),checks:['page rendering','heading structure','internal links','local assets','complete case media','email body generation'],browserLayoutTested:false},null,2));
